// Generated by CoffeeScript 1.6.1
(function() {
  var echo;

  echo = function(x) {
    console.log(x);
    return $(".message").text(x);
  };

  $(function() {
    var skirtline;
    skirtline = false;
    $(".square").resizable().draggable();
    $("#stop-first").click(function() {
      var action, sq;
      sq = $(".square");
      if (skirtline) {
        action = "enable";
      } else {
        action = "disable";
      }
      sq.resizable(action);
      sq.draggable(action);
      return skirtline = !skirtline;
    });
    $(".square").click(function(e) {
      var bottomsq, clicked_point, img, main, sqheight, square, sqwidth, topsq;
      if (skirtline) {
        return false;
      }
      img = $("#main img");
      square = $(this);
      main = $("#main");
      sqwidth = square.width();
      sqheight = square.height();
      clicked_point = e.pageY - square.offset().top;
      topsq = $(".square .top");
      bottomsq = $(".square .bottom");
      topsq.css("display", "block").css("height", clicked_point);
      return bottomsq.css("display", "block").css("height", sqheight - clicked_point);
    });
    $("#stop-second").click(function() {
      var bottomsq, bottomsqW, img, square, topsq, topsqW;
      square = $(".square");
      img = $("#main > img");
      topsq = $(".square .top");
      bottomsq = $(".square .bottom");
      topsqW = $(".square .top .img-wrapper");
      bottomsqW = $(".square .bottom .img-wrapper");
      img.css("opacity", "0.5");
      topsqW.append("<img src='" + img.attr("src") + "' />");
      bottomsqW.append("<img src='" + img.attr("src") + "' />");
      topsq.y = topsq.offset().top - img.offset().top;
      topsq.x = topsq.offset().left - img.offset().left;
      $(".square .top .img-wrapper").css("width", img.width());
      $(".square .top .img-wrapper").css("height", img.height());
      $(".square .top .img-wrapper").css("top", -topsq.y);
      $(".square .top .img-wrapper").css("left", -topsq.x);
      bottomsq.y = bottomsq.offset().top - img.offset().top;
      bottomsq.x = bottomsq.offset().left - img.offset().left;
      $(".square .bottom .img-wrapper").css("width", img.width());
      $(".square .bottom .img-wrapper").css("height", img.height());
      $(".square .bottom .img-wrapper").css("top", -bottomsq.y);
      return $(".square .bottom .img-wrapper").css("left", -bottomsq.x);
    });
    $("#up").click(function() {
      var bottomsq, bottomsqW, bottomsq_height, bottomsq_top, diff, height, img, rate, square, topsq, topsqW, topsq_height, topsq_top;
      rate = 0.1;
      square = $(".square");
      img = $("#main > img");
      topsq = $(".square .top");
      topsq_height = topsq.height();
      bottomsq = $(".square .bottom");
      bottomsq_height = bottomsq.height();
      topsqW = $(".square .top .img-wrapper");
      bottomsqW = $(".square .bottom .img-wrapper");
      topsq_top = topsqW.css("top");
      bottomsq_top = bottomsqW.css("top");
      diff = topsq_height * rate;
      $(".square .top").css("height", topsq_height - diff);
      $(".square .bottom").css("height", bottomsq_height + diff);
      img = $(".square .top .img-wrapper img");
      height = img.css("height");
      height = parseInt(height.slice(0, -2), 10);
      $(".square .top .img-wrapper").css("width", img.width());
      $(".square .top .img-wrapper").css("height", height - diff);
      $(".square .top .img-wrapper img").css("width", img.width());
      $(".square .top .img-wrapper img").css("height", height - diff);
      topsq.y = topsq_top * (topsq.height() / topsq_height);
      topsq.x = topsq.offset().left - img.offset().left;
      $(".square .top .img-wrapper").css("top", -topsq.y + 1);
      $(".square .top .img-wrapper").css("left", -topsq.x);
      img = $(".square .bottom .img-wrapper img");
      height = img.css("height");
      height = parseInt(height.slice(0, -2), 10);
      $(".square .bottom .img-wrapper").css("width", img.width());
      $(".square .bottom .img-wrapper").css("height", height + diff);
      $(".square .bottom .img-wrapper img").css("width", img.width());
      $(".square .bottom .img-wrapper img").css("height", height + diff);
      bottomsq.y = bottomsq_top * (bottomsq.height() / bottomsq_height);
      bottomsq.x = bottomsq.offset().left - img.offset().left;
      $(".square .bottom .img-wrapper").css("top", -bottomsq.y + 1);
      return $(".square .bottom .img-wrapper").css("left", -bottomsq.x);
    });
    $("#finish").click(function() {
      var bottom_left, bottom_top, img, top_left, top_top;
      img = $("#main > img");
      img.css("opacity", "1");
      $(".square .top").css("border", "none");
      $(".square").css("border", "none");
      top_top = $(".square .top .img-wrapper").css("top");
      top_top = parseInt(top_top.slice(0, -2), 10);
      top_left = $(".square .top .img-wrapper").css("left");
      top_left = parseInt(top_left.slice(0, -2), 10);
      bottom_top = $(".square .bottom .img-wrapper").css("top");
      bottom_top = parseInt(bottom_top.slice(0, -2), 10);
      bottom_left = $(".square .bottom .img-wrapper").css("left");
      bottom_left = parseInt(bottom_left.slice(0, -2), 10);
      $(".square .top .img-wrapper").css("top", top_top + 2);
      $(".square .top .img-wrapper").css("left", top_left + 2);
      $(".square .bottom .img-wrapper").css("top", bottom_top + 2);
      return $(".square .bottom .img-wrapper").css("left", bottom_left + 2);
    });
    return $(".skirt_area .btn").click(function() {
      var name;
      name = $(this).attr("id");
      return $("#main > img").attr("src", "img/" + name + ".jpg");
    });
  });

}).call(this);
